### ISSUE TITLE
publish the extension to packagist ;)

### ISSUE THREAD

**Issue by Grummfy** [atoum/telemetry-extension#7]

**Comment by Hywan** [comment]
I don't have Packagist credentials. Maybe @jubianchi?

**Comment by mikaelrandy** [comment]
Same here.
I don't have credentials for this.

**Comment by vonglasow** [comment]
Hello @jubianchi do you have any update about this issue ?

Thanks

**Comment by jubianchi** [comment]
https://packagist.org/packages/atoum/telemetry-extension

**Comment by Grummfy** [comment]
Yihaaaa
